---
# tasks file for sap_hana_sr_takeover
#
- name: Verify the role variables
  ansible.builtin.import_tasks:
    file: assert_vars.yml

- name: Get HDB online state
  ansible.builtin.shell: |
    set -o pipefail
    source /usr/sap/{{ sap_hana_sr_takeover_sid | upper }}/home/.sapenv.sh && \
    /usr/sap/{{ sap_hana_sr_takeover_sid | upper }}/HDB{{ sap_hana_sr_takeover_instance_number }}/exe/hdbnsutil \
    -sr_state | awk '($1 == "online:") {print $2}'
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ sap_hana_sr_takeover_sid | lower }}adm"
  changed_when: false
  register: __sap_hana_sr_takeover_register_online_status
# Function sr_state can return following mode values:
# - 'none'                   - Host is not enabled for HSR
# - 'primary'                - Host is a primary system
# - 'sync'|'syncmem'|'async' - the HSR replication method on the secondary system

- name: Get the mode of the HDB system
  ansible.builtin.shell: |
    set -o pipefail
    source /usr/sap/{{ sap_hana_sr_takeover_sid | upper }}/home/.sapenv.sh && \
    /usr/sap/{{ sap_hana_sr_takeover_sid | upper }}/HDB{{ sap_hana_sr_takeover_instance_number }}/exe/hdbnsutil \
    -sr_state | awk '($1 == "mode:") {print $2}'
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ sap_hana_sr_takeover_sid | lower }}adm"
  changed_when: false
  register: __sap_hana_sr_takeover_mode

##
# enable the right primary
#
- name: Fail, when the planned primary system cannot take over (no HSR configured)
  ansible.builtin.fail:
    msg: "This system is not part of a SAP HANA system replication setup."
  when:
    - ansible_hostname == sap_hana_sr_takeover_primary
    - __sap_hana_sr_takeover_mode.stdout == "none"

- name: Promote SAP HANA system on {{ sap_hana_sr_takeover_primary }}
  ansible.builtin.shell: |
    source /usr/sap/{{ sap_hana_sr_takeover_sid | upper }}/home/.sapenv.sh && \
    /usr/sap/{{ sap_hana_sr_takeover_sid | upper }}/HDB{{ sap_hana_sr_takeover_instance_number }}/exe/hdbnsutil \
    -sr_takeover
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ sap_hana_sr_takeover_sid | lower }}adm"
  register: __sap_hana_sr_takeover_action
  changed_when: __sap_hana_sr_takeover_action.rc == 0
  failed_when: __sap_hana_sr_takeover_action.rc != 0
  when:
    - ansible_hostname == sap_hana_sr_takeover_primary
    - __sap_hana_sr_takeover_mode.stdout != "primary"
    - not sap_hana_sr_takeover_handshake

- name: Suspend old primary and promote SAP HANA system on {{ sap_hana_sr_takeover_primary }}
  ansible.builtin.shell: |
    source /usr/sap/{{ sap_hana_sr_takeover_sid | upper }}/home/.sapenv.sh && \
    /usr/sap/{{ sap_hana_sr_takeover_sid | upper }}/HDB{{ sap_hana_sr_takeover_instance_number }}/exe/hdbnsutil \
    -sr_takeover --suspendPrimary
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ sap_hana_sr_takeover_sid | lower }}adm"
  register: __sap_hana_sr_takeover_action
  changed_when: __sap_hana_sr_takeover_action.rc == 0
  failed_when: __sap_hana_sr_takeover_action.rc != 0
  when:
    - ansible_hostname == sap_hana_sr_takeover_primary
    - __sap_hana_sr_takeover_mode.stdout != "primary"
    - sap_hana_sr_takeover_handshake

###
# register the secondary
#
- name: Register 'sap_hana_sr_takeover_secondary' to the new primary system
  become: true
  become_user: "{{ sap_hana_sr_takeover_sid | lower }}adm"
  when:
    - ansible_hostname == sap_hana_sr_takeover_secondary
    - __sap_hana_sr_takeover_mode.stdout != sap_hana_sr_takeover_rep_mode
  block:
    - name: Stop HDB on {{ sap_hana_sr_takeover_secondary }}
      ansible.builtin.shell: |
        source /usr/sap/{{ sap_hana_sr_takeover_sid | upper }}/home/.sapenv.sh && \
        /usr/sap/{{ sap_hana_sr_takeover_sid | upper }}/HDB{{ sap_hana_sr_takeover_instance_number }}/HDB stop
      args:
        executable: /bin/bash
      register: __sap_hana_sr_takeover_stop
      changed_when: __sap_hana_sr_takeover_stop.rc == 0
      failed_when: __sap_hana_sr_takeover_stop.rc != 0
      when:
        - __sap_hana_sr_takeover_register_online_status.stdout == 'true'

    - name: Register secondary HDB on {{ sap_hana_sr_takeover_secondary }}
      ansible.builtin.shell: |
        source /usr/sap/{{ sap_hana_sr_takeover_sid | upper }}/home/.sapenv.sh && \
        /usr/sap/{{ sap_hana_sr_takeover_sid | upper }}/HDB{{ sap_hana_sr_takeover_instance_number }}/exe/hdbnsutil \
        -sr_register \
        --name="{{ sap_hana_sr_takeover_sitename }}" \
        --remoteHost={{ sap_hana_sr_takeover_primary }} \
        --remoteInstance={{ sap_hana_sr_takeover_instance_number }} \
        --replicationMode={{ sap_hana_sr_takeover_rep_mode }} \
        --operationMode={{ sap_hana_sr_takeover_hsr_oper_mode }}
      args:
        executable: /bin/bash
      register: __sap_hana_sr_takeover_action
      changed_when: __sap_hana_sr_takeover_action.rc == 0
      failed_when: __sap_hana_sr_takeover_action.rc != 0

## Check Online state and start HDB
- name: Get the HDB online state
  ansible.builtin.shell: |
    set -o pipefail
    source /usr/sap/{{ sap_hana_sr_takeover_sid | upper }}/home/.sapenv.sh && \
    /usr/sap/{{ sap_hana_sr_takeover_sid | upper }}/HDB{{ sap_hana_sr_takeover_instance_number }}/exe/hdbnsutil \
    -sr_state | awk '($1 == "online:") {print $2}'
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ sap_hana_sr_takeover_sid | lower }}adm"
  changed_when: false
  register: __sap_hana_sr_takeover_register_online_status

- name: Ensure that HDB is running
  ansible.builtin.shell: |
    source /usr/sap/{{ sap_hana_sr_takeover_sid | upper }}/home/.sapenv.sh && \
    /usr/sap/{{ sap_hana_sr_takeover_sid | upper }}/HDB{{ sap_hana_sr_takeover_instance_number }}/HDB start
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ sap_hana_sr_takeover_sid | lower }}adm"
  register: __sap_hana_sr_takeover_start
  changed_when: __sap_hana_sr_takeover_start.rc == 0
  failed_when: __sap_hana_sr_takeover_start.rc != 0
  when:
    - __sap_hana_sr_takeover_register_online_status.stdout == 'false'
